# Generated by Django 3.0.7 on 2021-08-18 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='photo',
        ),
    ]
