# Generated by Django 3.0.7 on 2021-08-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_remove_animal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(default=True, upload_to='photo/'),
        ),
    ]
