# Generated by Django 3.0.7 on 2021-08-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank='True', upload_to='photo/'),
        ),
    ]
