# Generated by Django 3.0.7 on 2021-08-18 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20210818_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
            ],
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'животное', 'verbose_name_plural': 'животные'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='appearence',
            field=models.TextField(blank=True, verbose_name='Внешность'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='available',
            field=models.BooleanField(default=False, verbose_name='В поисках дома'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, verbose_name='Особенности опведения'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(max_length=6, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank='True', upload_to='photo/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='animal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='animals.Category', verbose_name='Категория'),
        ),
    ]
