# Generated by Django 3.0.7 on 2021-08-18 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_auto_20210818_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.Category', verbose_name='Category'),
        ),
    ]
