# Generated by Django 3.0.7 on 2021-08-18 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_auto_20210818_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='curator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='animals.Curator'),
        ),
        migrations.AddField(
            model_name='curator',
            name='description',
            field=models.TextField(blank=True, verbose_name='About curator'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, default='A very nice pet!', verbose_name='Character'),
        ),
    ]
