# Generated by Django 3.0.7 on 2021-08-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_auto_20210818_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='curator',
            name='organization',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curator',
            name='photo',
            field=models.ImageField(blank='True', upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='curator',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Curator'),
        ),
    ]
