# Generated by Django 3.0.7 on 2021-08-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0016_auto_20210820_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(db_index=True, max_length=35),
        ),
    ]
