# Generated by Django 3.0.7 on 2021-08-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0017_auto_20210820_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='available',
            field=models.BooleanField(default=True, verbose_name='In home searching'),
        ),
    ]
