# Generated by Django 3.0.7 on 2021-08-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0018_auto_20210821_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/category'),
        ),
    ]
