# Generated by Django 3.0.7 on 2021-08-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0019_category_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('photo', models.ImageField(blank='True', upload_to='photo/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
