# Generated by Django 3.0.7 on 2021-08-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0020_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='back_photo',
            field=models.ImageField(blank=True, upload_to='photo/bphoto'),
        ),
    ]
